gitlabUrl: https://gitlab.com/

rbac:
  create: true

runners:
  serviceAccountName: gitlab-runner
  privileged: true
  builds:
    cpuLimit: 1000m
    cpuRequests: 100m
    memoryLimit: 2Gi
    memoryRequests: 256Mi
  config: |
    [[runners]]
      [runners.kubernetes]
        image = "alpine:latest"
        namespace_overwrite_allowed = "devops-tools"
        service_account_overwrite_allowed = "gitlab-deployer"