apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-cross-ns-deployer
subjects:
- kind: ServiceAccount
  name: jenkins-deployer
  namespace: devops-tools
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io