apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.reviews.service.name }}"
  labels:
    app: reviews
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.reviews.service.port }}
    name: http
  selector:
    app: reviews
