spec:
  inputs:
    release_version:
      description: "Enter version for Prod (e.g., 1.2.0)"
    target_service:
      description: "Which service are you releasing?"
      options:
        - "productpage"
        - "details"
        - "ratings"
        - "reviews"
        - "none"

---

stages:
  - triggers

trigger_productpage:
  stage: triggers
  trigger:
    include: src/productpage/.gitlab-ci.yml
    strategy: depend
  variables:
    RELEASE_VERSION: $[[ inputs.release_version ]]
  rules:
    - if: '$[[ inputs.target_service ]] == "productpage"'
  #  - changes:
  #    - src/productpage/**/*