externalURL: https://registry-supeem.opsta.in.th

expose:
  type: ingress
  tls:
    enabled: true
    certSource: secret
    secret:
      secretName: harbor-cert
  ingress:
    hosts:
      core: registry-supeem.opsta.in.th
    className: nginx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/proxy-body-size: "0"
      nginx.ingress.kubernetes.io/proxy-read-timeout: "900"
      nginx.ingress.kubernetes.io/proxy-send-timeout: "900"

core:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"   
      cpu: "1000m"   

jobservice:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "1Gi"
      cpu: "1000m"

registry:
  replicas: 1
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "2Gi"  
      cpu: "1000m"

trivy:
  enabled: true
  replicas: 1
  resources:
    requests:
      memory: "1Gi"  
      cpu: "200m"
    limits:
      memory: "3Gi"   
      cpu: "2000m" 

database:
  type: internal
  internal:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

redis:
  type: internal
  internal:
    resources:
      requests:
        memory: "256Mi"
        cpu: "100m"
      limits:
        memory: "1Gi"
        cpu: "1000m"

persistence:
  enabled: true
  resourcePolicy: "keep"
  persistentVolumeClaim:
    registry:
      size: 20Gi  
    jobservice:
      size: 2Gi
    database:
      size: 2Gi
    redis:
      size: 2Gi
    trivy:
      size: 10Gi