pipeline {
    agent {
        kubernetes {
            yaml """
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: jenkins-agent-bookinfo
spec:
  serviceAccountName: jenkins-deployer
  containers:
  - name: docker
    image: docker:24.0.5
    command: ['cat']
    tty: true
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
  - name: dind
    image: docker:24.0.5-dind
    command: ["dockerd", "--host=unix:///var/run/docker.sock", "--host=tcp://0.0.0.0:2375", "--storage-driver=overlay2"]
    securityContext:
      privileged: true
    env:
    - name: DOCKER_TLS_CERTDIR
      value: ""
  - name: helm
    image: alpine/helm:3.12.0
    command: ['cat']
    tty: true
  - name: sonar-scanner
    image: sonarsource/sonar-scanner-cli:latest
    command: ['cat']
    tty: true
  - name: dependency-check
    image: owasp/dependency-check:latest
    command: ['cat']
    tty: true
    securityContext:
      runAsUser: 0
    volumeMounts:
    - name: sca-data
      mountPath: /usr/share/dependency-check/data
      subPath: "bookinfo-scan"
  - name: trivy
    image: aquasec/trivy:latest
    command: ['cat']
    env:
    - name: DOCKER_HOST
      value: tcp://localhost:2375
    tty: true
  - name: zap
    image: ghcr.io/zaproxy/zaproxy:stable
    command: ['sh', '-c', 'cat']
    tty: true
  - name: kics
    image: checkmarx/kics:latest
    command: ['cat']
    tty: true
  volumes:
  - name: sca-data
    hostPath:
      path: /tmp/dependency-check-data
"""
        }
    }

    environment {
        REGISTRY_URL = "registry-supeem.opsta.in.th"
        IMAGE_PATH   = "library/reviews-service"
        FULL_IMAGE   = "${REGISTRY_URL}/${IMAGE_PATH}"

        CHART_DIR    = "helm-chart/reviews"

        SAFE_BRANCH  = "${env.BRANCH_NAME != null ? env.BRANCH_NAME : 'dev'}"
        RELEASE_NAME = "${env.SAFE_BRANCH == 'main' ? 'bookinfo-reviews-uat' : 'bookinfo-reviews-dev'}"
        NAMESPACE    = "${env.SAFE_BRANCH == 'main' ? 'bookinfo-uat' : 'bookinfo-dev'}"
        VALUES_FILE  = "${env.SAFE_BRANCH == 'main' ? 'helm-chart/reviews/uat-reviews-values.yaml' : 'helm-chart/reviews/dev-reviews-values.yaml'}"

        SONAR_SERVER_URL = "https://sast-supeem.opsta.in.th"
        SONAR_PROJECT_KEY = "${env.SAFE_BRANCH == 'main' ?  'bookinfo-reviews' : 'bookinfo-reviews-dev'}"

        APP_URL      = "http://${RELEASE_NAME}.${NAMESPACE}.svc.cluster.local:9080"
    }

    stages {
        stage('Checkout & Setup') {
            steps {
                script {
                    checkout([$class: 'GitSCM',
                        branches: [[name: "*/${env.SAFE_BRANCH}"]], 
                        userRemoteConfigs: [[
                            credentialsId: 'bookinfo-deploy-key',
                            url: 'git@gitlab.com:SupeemAFK/bookinfo.git'
                        ]]
                    ])
                    env.GIT_TAG = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                }
            }
        }

        
        stage('IaC Scan (KICS)') {
            steps {
                container('kics') {
                    sh "/app/bin/kics scan -p ${env.CHART_DIR} --fail-on high,critical --report-formats html,json -o ."
                }
            }
            post {
                always {
                    script {
                        if (fileExists('results.html')) { 
                            archiveArtifacts artifacts: 'results.html,results.json', fingerprint: true
                            publishHTML([
                                allowMissing: false,
                                alwaysLinkToLastBuild: true,
                                keepAll: true,
                                reportDir: '.',
                                reportFiles: 'results.html',
                                reportName: 'KICS IaC Report'
                            ])
                        }
                    }
                }
            }
        }

        stage('Static Analysis (SonarQube)') {
            steps {
                container('sonar-scanner') {
                    withCredentials([string(credentialsId: 'sonarqube-token', variable: 'SONAR_TOKEN')]) {
                        sh '''
                            sonar-scanner \
                            -Dsonar.projectKey=${SONAR_PROJECT_KEY} \
                            -Dsonar.sources=src/reviews/src/main/java \
                            -Dsonar.java.binaries=src/reviews/bin/main \
                            -Dsonar.host.url=${SONAR_SERVER_URL} \
                            -Dsonar.login=${SONAR_TOKEN} \
                            -Dsonar.qualitygate.wait=true \
                            -Dsonar.qualitygate.timeout=300
                        '''
                    }
                }
            }
        }

        stage('SCA (Dependency-Check)') {
            steps {
                container('dependency-check') {
                    sh '''                        
                        /usr/share/dependency-check/bin/dependency-check.sh \
                        --project "Bookinfo-reviews" \
                        --scan ./src/reviews/build.gradle \
                        --format HTML \
                        --format XML \
                        --enableExperimental \
                        --out .
                    '''
                }
            }
            post {
                always {
                    dependencyCheckPublisher pattern: '**/dependency-check-report.xml'                    
                }
            }
        }

        stage('Build & Push to Harbor') {
            steps {
                container('docker') {
                    script {
                        // Wait for the private daemon to finish booting.
                        sh 'while ! docker info > /dev/null 2>&1; do sleep 1; done'

                        withCredentials([usernamePassword(credentialsId: 'registry-bookinfo', usernameVariable: 'REG_USER', passwordVariable: 'REG_PASS')]) {
                            sh 'echo $REG_PASS | docker login ${REGISTRY_URL} -u "$REG_USER" --password-stdin'

                            sh "docker build -t ${env.FULL_IMAGE}:${env.GIT_TAG} ./src/reviews"

                            retry(3) {
                                try {
                                    sh "docker push ${env.FULL_IMAGE}:${env.GIT_TAG}"
                                } 
                                catch (Exception e) {
                                    echo "Push failed, likely 500 error. Waiting 15s before retry..."
                                    sleep 15
                                    throw e 
                                }
                            }
                            
                            sh 'docker logout ${REGISTRY_URL}'
                        }
                    }
                }
            }
        }

        stage('Image Scan (Trivy)') {
            steps {
                container('trivy') {
                    sh "trivy image --severity HIGH,CRITICAL --format template --template '@/contrib/html.tpl' -o trivy-results.html ${env.FULL_IMAGE}:${env.GIT_TAG}"
                    sh """
                        mkdir -p trivy-html-report
                        cp trivy-results.html trivy-html-report/index.html
                        chmod -R 755 trivy-html-report
                    """
                }
            }
            post {
                always {
                    script {
                        if (fileExists('trivy-html-report/index.html')) {
                            archiveArtifacts artifacts: 'trivy-results.html', fingerprint: true
                            publishHTML([
                                allowMissing: false,
                                alwaysLinkToLastBuild: true,
                                keepAll: true,
                                reportDir: 'trivy-html-report',
                                reportFiles: 'index.html',
                                reportName: 'Trivy-Image-Scan'
                            ])
                        }
                    }
                }
            }
        }

        stage('Deploy to K8s (Helm)') {
            steps {
                container('helm') {
                    sh """                       
                        helm upgrade --install ${env.RELEASE_NAME} ${env.CHART_DIR} \
                            --namespace ${env.NAMESPACE} \
                            -f ${env.VALUES_FILE} \
                            --set reviews.image.tag=${env.GIT_TAG} \
                            --wait
                    """
                }
            }
        }

        stage('DAST (OWASP ZAP)') {
            steps {
                container('zap') {
                    script {
                        sh '''
                            echo "Waiting for Reviews service to be ready..."

                            for i in {1..30}; do
                                STATUS=$(curl -s -o /dev/null -w "%{http_code}" http://bookinfo-reviews-dev.bookinfo-dev.svc.cluster.local:9080/reviews)
                                
                                if [ "$STATUS" -eq "200" ]; then
                                echo "Service is UP (HTTP 200). Starting ZAP scan..."
                                exit 0
                                fi
                                
                                echo "Service returned HTTP $STATUS. Retrying in 5s..."
                                sleep 5
                            done

                            echo "Service failed to become ready in time."
                            exit 1
                        '''

                        sh "chmod 777 ."
                        sh "ln -s \$(pwd) /zap/wrk"

                        sh """
                            zap-baseline.py -t ${env.APP_URL} \
                            -r zap-report.html \
                            --autooff \
                            -I \
                            -z "-config connection.timeoutInSecs=60"
                        """

                        if (fileExists('zap-report.html')) {
                            sh "mkdir -p zap-out && cp zap-report.html zap-out/index.html && chmod -R 755 zap-out"
                        } 
                        else {
                            echo "ZAP Failed. Running debug..."
                            sh "nslookup \$(echo ${env.APP_URL} | sed 's|http://||' | cut -d: -f1)"
                        }
                    }
                }
            }
            post {
                always {
                    script {
                        if (fileExists('zap-out/index.html')) {
                            archiveArtifacts artifacts: 'zap-report.html', fingerprint: true
                            publishHTML([
                                allowMissing: false,
                                alwaysLinkToLastBuild: true,
                                keepAll: true,
                                reportDir: 'zap-out',
                                reportFiles: 'index.html',
                                reportName: 'OWASP-ZAP-DAST'
                            ])
                        }
                    }
                }
            }
        }
    }
}