stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN! Building the application..."
  
test-job1:
  stage: test
  script:
    - echo "Running tests..."

test-job2:
  stage: test
  script:
    - echo "Running more tests, this one takes longer..."

deploy-prod:
  stage: deploy
  script:
    - echo "Deploying to production from the $CI_COMMIT_BRANCH branch."
