apiVersion: v1
kind: Service
metadata:
  name: "{{ .Values.details.service.name }}"
  labels:
    app: details
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.details.service.port }}
    name: http
  selector:
    app: details
